In [132]:
image_path = "ex.tif" # Path to the tif image
threshold = 1 # threshold (inclusive) for detection of a protein

In [133]:
import cv2
import numpy as np
from scipy.signal import convolve2d
from PIL import Image

In [134]:
# Test image
# image = np.array([
#     [0, 1, 1, 0, 0, 0, 0],
#     [0, 1, 0, 0, 0, 0, 1],
#     [0, 0, 0, 0, 0, 0, 0],
#     [0, 1, 0, 0, 0, 0, 0],
#     [1, 1, 0, 0, 0, 1, 0],
# ], dtype=np.uint8)

# Reading image
image = Image.open('ex.tif')
image = np.array(image)
image = image >= threshold
image = image.astype(np.uint8)
image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [135]:
# Defining the kernels
# The open close kernel
growing_kernel = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
], dtype=np.uint8)

# Kernel for detecting aggregates
aggregation_kernel = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1],
], dtype=np.uint8)

In [136]:
# Closing for filling gaps
closed = cv2.morphologyEx(image, cv2.MORPH_CLOSE, growing_kernel)

# Opening in order not to have a extended region more than the closed gaps
opened = cv2.morphologyEx(closed, cv2.MORPH_OPEN, growing_kernel)


opened

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=uint8)

In [137]:
# Detecting the aggregates
aggregates = convolve2d(opened, aggregation_kernel)

aggregates = aggregates >= 1

aggregates = aggregates[1:-1, 1:-1]

aggregates.astype(np.uint8)

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 1]], dtype=uint8)

In [138]:
# Removing aggregates
image[aggregates] = 0

image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)